#!/bin/bash

# =============================================================================
# MOSTRAR ESTRUTURA DOS MANIFESTS - ProntDental
# =============================================================================

echo "📁 Estrutura dos Manifests Kubernetes - ProntDental"
echo "==================================================="

echo ""
echo "🏗️  Estrutura Organizada por Ambiente:"
echo "========================================"

echo ""
echo "📂 k8s-manifests/"
echo "├── 📁 development/       # Ambiente de Desenvolvimento"
echo "│   ├── 📁 cnpg/         # PostgreSQL com CNPG"
echo "│   │   ├── cnpg-operator.yaml"
echo "│   │   ├── cnpg-webhook.yaml"
echo "│   │   ├── postgresql-dev-cluster.yaml"
echo "│   │   ├── postgresql-dev-backup.yaml"
echo "│   │   └── postgresql-secret.yaml"
echo "│   ├── 📁 pgadmin/      # pgAdmin DEV"
echo "│   │   ├── pgadmin-dev-deployment.yaml"
echo "│   │   ├── pgadmin-dev-service.yaml"
echo "│   │   └── pgadmin-dev-ingress.yaml"
echo "│   └── 📁 minio/        # MinIO DEV"
echo "│       ├── minio-dev-deployment.yaml"
echo "│       ├── minio-dev-service.yaml"
echo "│       └── minio-dev-ingress.yaml"
echo "├── 📁 production/        # Ambiente de Produção"
echo "│   ├── 📁 pgadmin/      # pgAdmin PROD"
echo "│   │   ├── pgadmin-deployment.yaml"
echo "│   │   ├── pgadmin-service.yaml"
echo "│   │   └── pgadmin-ingress.yaml"
echo "│   └── 📁 minio/        # MinIO PROD"
echo "│       ├── minio-deployment.yaml"
echo "│       ├── minio-service.yaml"
echo "│       └── minio-ingress.yaml"
echo "├── 📁 shared/           # Recursos Compartilhados"
echo "│   └── 📁 ingress/      # Ingress Controllers"
echo "│       ├── nginx-ingress-controller.yaml"
echo "│       ├── nginx-ingress-controller-arm.yaml"
echo "│       └── traefik-ingress-controller.yaml"
echo "└── 📁 monitoring/       # Monitoramento (futuro)"

echo ""
echo "🚀 Scripts de Deploy:"
echo "====================="
echo "• ./scripts/deploy/deploy-development.sh  # Deploy ambiente DEV"
echo "• ./scripts/deploy/deploy-production.sh   # Deploy ambiente PROD"
echo "• ./scripts/deploy/dev-status.sh           # Status ambiente DEV"

echo ""
echo "📋 Comandos de Deploy:"
echo "====================="
echo ""
echo "🔧 Recursos Comuns:"
echo "kubectl apply -f common/cnpg/"
echo "kubectl apply -f common/monitoring/"
echo ""
echo "🔧 Ambiente de Desenvolvimento:"
echo "kubectl apply -f k8s-manifests/development/pgadmin/"
echo "kubectl apply -f k8s-manifests/development/minio/"
echo ""
echo "🏭 Ambiente de Produção:"
echo "kubectl apply -f k8s-manifests/production/pgadmin/"
echo "kubectl apply -f k8s-manifests/production/minio/"
echo ""
echo "🔗 Ingress Controllers:"
echo "kubectl apply -f k8s-manifests/shared/ingress/"

echo ""
echo "✅ Estrutura organizada com sucesso!"
