apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-auth-secret
  namespace: ptcc-development
  labels:
    app: pgadmin-dev
    project: "ProntDental"
    environment: "development"
type: Opaque
data:
  # Credenciais do pgAdmin (base64 encoded)
  PGADMIN_EMAIL: YWRtaW5AcHJvbnRjbGluaWMuY29t  # admin@prontclinic.com
  PGADMIN_PASSWORD: UHJvbnRDbGluaWMyMDI1  # ProntClinic2025
