apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-tls
  namespace: ptcc-development
  labels:
    app: pgadmin-dev
    project: "ProntDental"
    environment: "development"
type: kubernetes.io/tls
data:
  # Certificado e chave privada para pgadmin-d.prontclinic.com.br
  # Estes são certificados auto-assinados para desenvolvimento
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWUyZ0F3SUJBZ0lJQk1qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxSUVtbHZwUHk5M2xjNVl0WEJvVVVMWW1hSnFxakpacTMyQlZHZmFv
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2V3a3dEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcUlFbWx2cFB5OTNsYzVZdFhCb1VVTFltaUpxcWpKWnEzMkJWR2Zhbw==
