apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-basic-auth
  namespace: ptcc-development
  labels:
    app: pgadmin-dev
    project: "ProntDental"
    environment: "development"
type: Opaque
data:
  # Usuário: admin, Senha: ProntClinic2025
  # Gerado com htpasswd: admin:$1$GNaFJAxV$kOhMp0YFiZiCSohobKGmS/
  auth: YWRtaW46JDEkR05hRkpBeFYka09oTXAwWUZpWmlDU29ob2JLR21TLw==
