apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-dev-pvc
  namespace: ptcc-development
  labels:
    app: minio-dev
    project: "ProntClinic"
    environment: "development"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: oci-bv
