export type SrcSpecialty = {
  name: string;
};

export type SrcTreatment = {
  name: string;
  value: number;
};

export type SrcSpecialtyWithTreatments = {
  specialty: SrcSpecialty;
  treatments: SrcTreatment[];
};

export const specialties: SrcSpecialtyWithTreatments[] = [
  {
    specialty: {
      name: 'Urgência',
    },
    treatments: [
      { name: 'Colagem de Fragmentos Dentários', value: 150.0 },
      { name: 'Consulta Odontológica de Urgência', value: 100.0 },
      { name: 'Consulta Odontológica de Urgência 24 horas', value: 150.0 },
      {
        name: 'Controle de Hemorragia com Aplicação de Agente Hemostático',
        value: 100.0,
      },
      {
        name: 'Controle de Hemorragia sem Aplicação de Agente Hemostático',
        value: 100.0,
      },
      { name: 'Imobilização Dentária em Dentes Decíduos', value: 150.0 },
      { name: 'Imobilização Dentária em Dentes Permanentes', value: 150.0 },
      { name: 'Incisão e Drenagem Extra Oral de Abscesso', value: 100.0 },
      { name: 'Incisão e Drenagem Intra Oral de Abscesso', value: 80.0 },
      { name: 'Recimentação de Trabalhos Protéticos', value: 45.0 },
      { name: 'Redução Simples de Luxação de ATM', value: 150.0 },
      { name: 'Reimplante Dentário com Contenção', value: 150.0 },
      { name: 'Sutura de Ferida', value: 60.0 },
      { name: 'Tratamento de Abscesso Periodontal agudo', value: 80.0 },
      { name: 'Tratamento de Alveolite', value: 80.0 },
    ],
  },
  {
    specialty: {
      name: 'Testes e exames laboratoriais',
    },
    treatments: [
      {
        name: 'Diagnóstico Anatomopatológico em Citologia Esfoliativa',
        value: 120.0,
      },
      {
        name: 'Diagnóstico Anatomopatológico em Material de Biópsia',
        value: 140.0,
      },
      { name: 'Diagnóstico Anatomopatológico em Peça Cirurgica', value: 140.0 },
      { name: 'Diagnóstico Anatomopatológico em Punção', value: 50.0 },
      { name: 'Diagnóstico por Meio de Enceramento', value: 50.0 },
      { name: 'Teste de Fluxo Salivar', value: 50.0 },
      { name: 'Teste de PH da Saliva', value: 50.0 },
    ],
  },
  {
    specialty: {
      name: 'Radiologia',
    },
    treatments: [
      { name: 'Fotografia - Unidade', value: 15.0 },
      { name: 'Levantamento Radiográfico', value: 150.0 },
      { name: 'Modelos Ortodônticos- Par', value: 75.0 },
      { name: 'Radiografia da Mão (Carpal)', value: 75.0 },
      { name: 'Radiografia de ATM', value: 130.0 },
      { name: 'Radiografia Interproximal - Bite-Wing', value: 15.0 },
      { name: 'Radiografia Oclusal', value: 30.0 },
      { name: 'Radiografia Panorâmica', value: 70.0 },
      { name: 'Radiografia Panorâmica com Traçado Cefalométrico', value: 70.0 },
      { name: 'Radiografia Periapical', value: 15.0 },
      { name: 'Radiografia póstero-anterior', value: 70.0 },
      { name: 'Teleradiografia com Traçado', value: 85.0 },
      { name: 'Teleradiografia sem Traçado', value: 70.0 },
      { name: 'Tomografia', value: 200.0 },
      { name: 'Traçado Cefalométrico', value: 30.0 },
    ],
  },
  {
    specialty: {
      name: 'Prótese',
    },
    treatments: [
      { name: 'Coroa de Acetato', value: 100.0 },
      { name: 'Coroa de Acetato em Dente Decíduo', value: 100.0 },
      { name: 'Coroa de Aço', value: 160.0 },
      { name: 'Coroa de Aço em Dente Decíduo', value: 160.0 },
      { name: 'Coroa de Policarbonato', value: 100.0 },
      { name: 'Coroa de Policarbonato em Dente Decíduo', value: 100.0 },
      { name: 'Coroa Provisória com Pino', value: 130.0 },
      { name: 'Coroa Provisória sem Pino', value: 110.0 },
      { name: 'Coroa Total Acrílica Prensada', value: 230.0 },
      { name: 'Coroa Total em Cerâmica Pura', value: 660.0 },
      { name: 'Coroa Total em Cerômero', value: 350.0 },
      { name: 'Coroa Total Metálica', value: 330.0 },
      { name: 'Coroa Total Metalo Cerâmica', value: 585.0 },
      { name: 'Coroa Total Metalo-Plástica', value: 230.0 },
      { name: 'Faceta em Cerâmica Pura', value: 575.0 },
      { name: 'Faceta em Cerômero', value: 300.0 },
      { name: 'Guia Cirúrgico para Prótese Imediata', value: 280.0 },
      { name: 'Núcleo Metálico Fundido', value: 200.0 },
      { name: 'Pino Pré Fabricado', value: 130.0 },
      { name: 'Prótese Fixa Adesiva Direta (provisória)', value: 250.0 },
      { name: 'Prótese Fixa Adesiva em Cerômero (metal free)', value: 500.0 },
      {
        name: 'Prótese Fixa Adesiva Indireta em Metálo Cerâmica 3 elementos',
        value: 1050.0,
      },
      {
        name: 'Prótese Fixa Adesiva Indireta em Metalo-Plástica 3 elementos',
        value: 755.0,
      },
      { name: 'Prótese Parcial Fixa em Metálo Cerâmica', value: 780.0 },
      { name: 'Prótese Parcial Fixa em Metálo Plástica', value: 600.0 },
      { name: 'Prótese Parcial Removível com Encaixes (PPR)', value: 1320.0 },
      {
        name: 'Prótese Parcial Removível com Grampos Bilateral (PPR)',
        value: 980.0,
      },
      { name: 'Prótese Parcial Removível Provisória (PPR)', value: 560.0 },
      { name: 'Prótese Total Imediata (PT)', value: 800.0 },
      { name: 'Prótese Total Incolor (PT)', value: 1250.0 },
      { name: 'Prótese Total (PT)', value: 1250.0 },
      { name: 'Provisório para Faceta', value: 70.0 },
      { name: 'Provisório para Inlay/Onlay', value: 50.0 },
      {
        name: 'Provisório para Restauração Metálica Fundida (RMF)',
        value: 50.0,
      },
      { name: 'Reembasamento de Coroa Provisória', value: 50.0 },
      {
        name: 'Reembasamento de Prótese Total ou Parcial em Consultório',
        value: 150.0,
      },
      {
        name: 'Reembasamento de Prótese Total ou Parcial em Laboratório',
        value: 290.0,
      },
      { name: 'Restauração Inlay', value: 250.0 },
      { name: 'Restauração Inlay em Cerâmica Pura', value: 570.0 },
      { name: 'Restauração Metálica Fundida', value: 285.0 },
      { name: 'Restauração Onlay', value: 250.0 },
      { name: 'Restauração Onlay em Cerâmica Pura', value: 570.0 },
    ],
  },
  {
    specialty: {
      name: 'Prevenção',
    },
    treatments: [
      { name: 'Aplicação de Cariostático', value: 40.0 },
      { name: 'Aplicação de Selante de Fóssulas e Fissuras', value: 45.0 },
      { name: 'Aplicação Tópica de Flúor', value: 50.0 },
      { name: 'Aplicação Tópica de Verniz Fluoretado', value: 40.0 },
      { name: 'Atividade Educativa em Saúde Bucal', value: 55.0 },
      { name: 'Atividade Educativa para Pais e/ou Cuidadores', value: 55.0 },
      {
        name: 'Atividade Educativa para Pais e/ou Cuidadores de pacientes Especiais',
        value: 55.0,
      },
      { name: 'Controle de Biofilme (Placa Bacteriana)', value: 40.0 },
      { name: 'Dessensibilização Dentária', value: 55.0 },
      { name: 'Mantenedor de espaço fixo', value: 270.0 },
      { name: 'Mantenedor de espaço removível', value: 270.0 },
      { name: 'Profilaxia + Polimento Coronário - Limpeza', value: 75.0 },
      { name: 'Remineralização Dentária', value: 40.0 },
    ],
  },
  {
    specialty: {
      name: 'Periodontia',
    },
    treatments: [
      { name: 'Ajuste Oclusal por Acréscimo', value: 80.0 },
      { name: 'Ajuste Oclusal por desgaste', value: 80.0 },
      { name: 'Aumento de Coroa Clínica', value: 180.0 },
      { name: 'Cirurgia Periodontal com Retalho', value: 190.0 },
      { name: 'Cunha Proximal', value: 170.0 },
      { name: 'Enxerto com Osso Liofilizado', value: 540.0 },
      { name: 'Enxerto Gengival Livre', value: 215.0 },
      { name: 'Enxerto Pediculado', value: 180.0 },
      { name: 'Gengivectomia', value: 170.0 },
      { name: 'Gengivoplastia', value: 170.0 },
      { name: 'Placa de mordida miorelaxante', value: 210.0 },
      { name: 'Raspagem Sub-gengival (RASUB)', value: 100.0 },
      { name: 'Raspagem Supra-gengival (RAP) - Limpeza', value: 90.0 },
      {
        name: 'Remoção dos Fatores de Retenção de Placa Bacteriana',
        value: 80.0,
      },
      { name: 'Tratamento de Fluorose - microabrasão', value: 80.0 },
      { name: 'Tratamento de Gengivite Necrosante Aguda (GNA)', value: 300.0 },
      { name: 'Tratamento de Pericoronarite', value: 100.0 },
      { name: 'Tunelização', value: 120.0 },
    ],
  },
  {
    specialty: {
      name: 'Outros',
    },
    treatments: [
      { name: 'Condicionamento em Odontologia', value: 50.0 },
      {
        name: 'Condicionamento em Odontologia para pacientes especiais',
        value: 50.0,
      },
      { name: 'Consulta de Auditoria - perícia final', value: 60.0 },
      { name: 'Consulta de Auditoria - perícia inicial', value: 60.0 },
      { name: 'Consulta de Retorno', value: 50.0 },
      { name: 'Consulta Inicial', value: 80.0 },
      { name: 'Consulta odontológica', value: 60.0 },
      { name: 'Falta a Consulta', value: 65.0 },
    ],
  },
  {
    specialty: {
      name: 'Ortodontia',
    },
    treatments: [
      { name: 'Aparelho Extra Bucal', value: 325.0 },
      { name: 'Aparelho Ortodôntico Fixo Metálico', value: 100.0 },
      { name: 'Aparelho Ortodôntico Fixo metálico Parcial', value: 100.0 },
      { name: 'Arco Lingual', value: 285.0 },
      { name: 'Bionator de Balters', value: 360.0 },
      { name: 'Contenção Fixa', value: 150.0 },
      { name: 'Disjuntor Palatino (Hirax)', value: 340.0 },
      { name: 'Disjuntor Palatino (Macnamara)', value: 290.0 },
      { name: 'Grade Palatina Fixa', value: 295.0 },
      { name: 'Grade Palatina Removível', value: 195.0 },
      { name: 'Manutenção de Aparelho Ortodôntico Fixo', value: 120.0 },
      { name: 'Manutenção de Aparelho Ortodôntico Removível', value: 90.0 },
      { name: 'Mascara Facial Delaire e Tração Reversa', value: 275.0 },
    ],
  },
  {
    specialty: {
      name: 'Implantodontia',
    },
    treatments: [
      {
        name: 'Cirurgia Odontológica com Aplicação de Aloenxertos',
        value: 2000.0,
      },
      { name: 'Coroa Provisória sobre Implante', value: 100.0 },
      {
        name: 'Coroa Total Livre de Metal (metal free) sobre Iimplante',
        value: 700.0,
      },
      { name: 'Coroa Total Metalo Cerâmica sobre Implante', value: 600.0 },
      { name: 'Coroa Total Metalo Plástica sobre Implante', value: 400.0 },
      { name: 'Guia Cirúrgico para Implante', value: 650.0 },
      { name: 'Implante Ortodôntico', value: 600.0 },
      { name: 'Instalação de cicatrizador', value: 50.0 },
      { name: 'Instalação de conexão de prótese cimentada', value: 80.0 },
      { name: 'Instalação de conexão de prótese parafusada', value: 80.0 },
      { name: 'Instalação de implante cone morse', value: 900.0 },
      { name: 'Instalação de implante hexágono externo', value: 850.0 },
      { name: 'Instalação de implante hexágono interno', value: 850.0 },
      { name: 'Instalação de Implante Ósseo Integrado', value: 900.0 },
      { name: 'Levantamento de seio', value: 1500.0 },
      { name: 'Levantamento de seio atraumático', value: 600.0 },
      { name: 'Prótese parcial removível implanto suportada', value: 1500.0 },
      { name: 'Prótese total removível implanto suportada', value: 1500.0 },
      { name: 'Protocolo inferior', value: 14000.0 },
      { name: 'Protocolo superior', value: 20000.0 },
    ],
  },
  {
    specialty: {
      name: 'Harmonização facial',
    },
    treatments: [
      { name: 'Bichectomia', value: 2500.0 },
      { name: 'Bioestimulador de colágeno', value: 1500.0 },
      { name: 'Fios de PDO liso', value: 1000.0 },
      { name: 'Fios de sustentação (espiculado)', value: 350.0 },
      { name: 'Lipo de papada cirúrgica', value: 1800.0 },
      { name: 'Lipo de papada enzimática', value: 350.0 },
      { name: 'MD codes', value: 1000.0 },
      { name: 'Microagulhamento', value: 350.0 },
      { name: 'Preenchimento de malar', value: 1000.0 },
      { name: 'Preenchimento de mandíbula', value: 1000.0 },
      { name: 'Preenchimento de mento', value: 1000.0 },
      { name: 'Preenchimento de olheiras', value: 1000.0 },
      {
        name: 'Preenchimento de sulco labiomentoniano (marionete)',
        value: 1000.0,
      },
      {
        name: 'Preenchimento do sulco nasogeniano (bigode chinês)',
        value: 1000.0,
      },
      { name: 'Preenchimento em fossa canina', value: 1000.0 },
      { name: 'Preenchimento labial', value: 1000.0 },
      { name: 'Preenchimento nas têmporas', value: 1000.0 },
      { name: 'Skinbooster', value: 400.0 },
      { name: 'Subcision', value: 400.0 },
      { name: 'Toxina botulínica (botox)', value: 1000.0 },
      { name: 'Ressecção de pele acima dos supercílios', value: 500.0 },
      { name: 'Frontoplastia endoscópica', value: 500.0 },
      { name: 'Frontoplastia aberta', value: 500.0 },
      { name: 'Blefaroplastia', value: 500.0 },
      { name: 'preenchimento com o ácido hialurônico', value: 1000.0 },
    ],
  },
  {
    specialty: {
      name: 'Endodontia',
    },
    treatments: [
      { name: 'Capeamento Pulpar Direto', value: 80.0 },
      { name: 'Curativo de Demora', value: 125.0 },
      { name: 'Preparo para Núcleo Intrarradicular', value: 70.0 },
      { name: 'Pulpectomia', value: 80.0 },
      { name: 'Pulpotomia', value: 100.0 },
      { name: 'Pulpotomia em dente decíduo', value: 100.0 },
      { name: 'Remoção de Corpo Estranho Intra-Canal', value: 120.0 },
      { name: 'Remoção de Material Obturador', value: 45.0 },
      { name: 'Remoção de Núcleo Intra-Radicular', value: 140.0 },
      { name: 'Remoção de Trabalho Protético', value: 140.0 },
      { name: 'Retratamento Endodôntico Birradicular', value: 360.0 },
      { name: 'Retratamento Endodôntico Multirradicular', value: 600.0 },
      { name: 'Retratamento Endodôntico Unirradicular', value: 260.0 },
      { name: 'Tratamento de Perfuração Endodôntica', value: 160.0 },
      { name: 'Tratamento Endodôntico Birradicular', value: 300.0 },
      {
        name: 'Tratamento Endodôntico de Dente com Rizogênese Incompleta',
        value: 100.0,
      },
      { name: 'Tratamento Endodôntico em Dente Decíduo', value: 180.0 },
      { name: 'Tratamento Endodôntico Multirradicular', value: 470.0 },
      { name: 'Tratamento Endodôntico Unirradicular', value: 240.0 },
    ],
  },
  {
    specialty: {
      name: 'Dentística',
    },
    treatments: [
      { name: 'Clareamento de Dente Desvitalizado', value: 170.0 },
      { name: 'Clareamento Dentário Caseiro', value: 340.0 },
      { name: 'Clareamento em Consultório', value: 240.0 },
      { name: 'Faceta em Resina Fotopolimerizável', value: 135.0 },
      { name: 'Núcleo de Preenchimento', value: 80.0 },
      { name: 'Placa de Clareamento', value: 200.0 },
      { name: 'Restauração Atraumática em Dente Decíduo', value: 50.0 },
      { name: 'Restauração Atraumática em Dente Permanente', value: 50.0 },
      { name: 'Restauração de Amálgama - 1 face', value: 70.0 },
      { name: 'Restauração de Amálgama - 2 faces', value: 90.0 },
      { name: 'Restauração de Amálgama - 3 faces', value: 100.0 },
      { name: 'Restauração de Amálgama - 4 faces', value: 120.0 },
      { name: 'Restauração em Ionômero de Vidro - 1 face', value: 60.0 },
      { name: 'Restauração em Ionômero de Vidro - 2 faces', value: 70.0 },
      { name: 'Restauração em Ionômero de Vidro - 3 faces', value: 75.0 },
      { name: 'Restauração em Ionômero de Vidro - 4 faces', value: 80.0 },
      { name: 'Restauração em Resina Fotopolimerizável 1 face', value: 65.0 },
      { name: 'Restauração em Resina Fotopolimerizável 2 faces', value: 80.0 },
      { name: 'Restauração em Resina Fotopolimerizável 3 faces', value: 100.0 },
      { name: 'Restauração em Resina Fotopolimerizável 4 faces', value: 120.0 },
      { name: 'Restauração Temporária (Expectante)', value: 60.0 },
    ],
  },
  {
    specialty: {
      name: 'Cirurgia',
    },
    treatments: [
      { name: 'Amputação Radicular com Obturação Retrógrada', value: 250.0 },
      { name: 'Amputação Radicular sem Obturação Retrógrada', value: 225.0 },
      {
        name: 'Apicetomia Birradiculares com Obturação Retrógrada',
        value: 280.0,
      },
      {
        name: 'Apicetomia Birradiculares sem Obturação Retrógrada',
        value: 255.0,
      },
      {
        name: 'Apicetomia Multirradiculares com Obturação Retrógrada',
        value: 325.0,
      },
      {
        name: 'Apicetomia Multirradiculares sem Obturação Retrógrada',
        value: 300.0,
      },
      {
        name: 'Apicetomia Unirradiculares com Obturação Retrógrada',
        value: 245.0,
      },
      {
        name: 'Apicetomia Unirradiculares sem Obturação Retrógrada',
        value: 220.0,
      },
      { name: 'Aumento de Vestíbulo Sulcoplastia', value: 145.0 },
      { name: 'Biópsia de Boca', value: 125.0 },
      { name: 'Biópsia de Glândula Salivar', value: 125.0 },
      { name: 'Biópsia de Lábio', value: 125.0 },
      { name: 'Biópsia de Língua', value: 125.0 },
      { name: 'Biópsia de Mandíbula', value: 130.0 },
      { name: 'Biópsia de Maxila', value: 130.0 },
      { name: 'Bridectomia', value: 150.0 },
      { name: 'Bridotomia', value: 150.0 },
      { name: 'Cirurgia com Retalho', value: 120.0 },
      { name: 'Cirurgia para Torus Mandibular Bilateral', value: 200.0 },
      { name: 'Cirurgia para Torus Mandibular Unilateral', value: 135.0 },
      { name: 'Cirurgia para Torus Palatinio', value: 170.0 },
      { name: 'Coleta por Raspagem em Lesões', value: 110.0 },
      { name: 'Controle Pós-operatório em Odontologia', value: 40.0 },
      { name: 'Enxerto Conjuntivo Subepitelial', value: 220.0 },
      { name: 'Exérese ou Excisão de Cálculo Salivar', value: 215.0 },
      { name: 'Exérese ou Excisão de Cistos Odontológicos', value: 130.0 },
      { name: 'Exérese ou Excisão de Mucocele', value: 145.0 },
      { name: 'Exérese ou Excisão de Rânula', value: 570.0 },
      { name: 'Exodontia com Odonto-Secção', value: 170.0 },
      { name: 'Exodontia com Retalho', value: 120.0 },
      { name: 'Exodontia de Dentes Inclusos / Impactados', value: 225.0 },
      { name: 'Exodontia de Dentes Semi-inclusos / impactados', value: 180.0 },
      {
        name: 'Exodontia de Permanente por Indicação Ortodôntica/protética',
        value: 100.0,
      },
      { name: 'Exodontia de Raiz Residual', value: 100.0 },
      { name: 'Exodontia Simples de Decíduo', value: 60.0 },
      { name: 'Exodontia Simples de Permanente', value: 100.0 },
      { name: 'Frenulectomia Lingual Frenectomia', value: 155.0 },
      { name: 'Frenulectonia Labial Frenectomia ', value: 155.0 },
      { name: 'Frenulotomia Labial Frenotomia', value: 155.0 },
      { name: 'Frenulotomia Lingual Frenotomia', value: 155.0 },
      { name: 'Punção Aspirativa', value: 140.0 },
      { name: 'Reconstrução de Sulco Gengivo-labial', value: 200.0 },
      { name: 'Redução Cruenta de Fratura Alvéolo Dentária', value: 170.0 },
      { name: 'Redução Incruenta de Fratura Alvéolo Dentária', value: 90.0 },
      { name: 'Remoção de tumores intra ósseos', value: 250.0 },
      { name: 'Sepultamento Radicular', value: 190.0 },
      {
        name: 'Tracionamento Cirúrgico com Finalidade Ortodôntica',
        value: 250.0,
      },
      { name: 'Tratamento Cirúrgico das Fístulas Buco-nasal', value: 245.0 },
      { name: 'Tratamento Cirúrgico das Fístulas Buco-sinusal', value: 245.0 },
      { name: 'Tratamento Cirúrgico de Bridas Constritivas', value: 165.0 },
      {
        name: 'Tratamento Cirúrgico de Hiperplasias de Tecidos Moles',
        value: 180.0,
      },
      {
        name: 'Tratamento Cirúrgico de Hiperplasias de Tecidos Ósseos',
        value: 240.0,
      },
      {
        name: 'Tratamento Cirúrgico de Tumores Benignos de Tecidos Ósseos',
        value: 240.0,
      },
      {
        name: 'Tratamento Cirúrgico dos Tumores Benignos de Tecidos Moles',
        value: 170.0,
      },
      {
        name: 'Tratamento Cirúrgico para Tumores Odontogênicos Benignos',
        value: 240.0,
      },
      { name: 'Tratamento Conservador de Luxação de ATM', value: 200.0 },
      { name: 'Ulectomia', value: 100.0 },
      { name: 'Ulotomia ', value: 100.0 },
    ],
  },
];
