apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  discord-webhook-url: "https://discord.com/api/webhooks/1434616055807873127/roVY8wNVy4Ay2uKrBydVVHlxXVDfKOto-TvWexKhz8yp_NI1eiSCBl1ti6WnB7IT5wHo"

