apiVersion: v1
kind: Secret
metadata:
  name: api-chat-d-secret
  namespace: ptcc-development
  labels:
    app: api-chat-d
    project: "ProntClinic"
    environment: "development"
type: Opaque
data:
  # API Key (base64 encoded)
  AUTHENTICATION_API_KEY: U3ZpdUxkbTlIcEM3dXRKalRnSWpMREVkVnJKSGdydDk1Wjd2SDhWZDh5NnB6R0VtbVhQNEZhcVI2M2ozRnE4Nw==
  
  # Database credentials
  DATABASE_USER: cHJvbnRjbGluaWM=  # prontclinic
  DATABASE_PASSWORD: cHJvbnRjbGluaWMxMjM=  # prontclinic123
  
  # S3/MinIO credentials (if enabled)
  S3_ACCESS_KEY: c3VhY2hhdmU=  # suachave
  S3_SECRET_KEY: c3VhY2hhdmU=  # suachave
