apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-chat-d-ingress
  namespace: ptcc-development
  labels:
    app: api-chat-d
    project: "ProntClinic"
    environment: "development"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-chat-d.prontclinic.com.br
    secretName: api-chat-d-tls
  rules:
  - host: api-chat-d.prontclinic.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-chat-d-combined-service
            port:
              number: 8080
