apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: ptcc-development
  labels:
    app: postgresql
    project: "ProntDental"
    environment: "development"
type: kubernetes.io/basic-auth
data:
  username: cHJvbnRjbGluaWM=  # prontclinic
  password: cHJvbnRjbGluaWMxMjM=  # prontclinic123
