apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgresql-scheduled-backup
  namespace: ptcc-development
  labels:
    app: postgresql
    project: "ProntDental"
    environment: "development"
spec:
  schedule: "0 2 * * *"  # Diariamente às 2h
  cluster:
    name: postgresql-cluster
  
  backupOwnerReference: self
  method: barmanObjectStore
