apiVersion: v1
kind: Secret
metadata:
  name: prontclinic-painel-secret
  namespace: ptcc-development
  labels:
    app: prontclinic-painel
    project: "ProntClinic"
    environment: "development"
type: Opaque
data:
  # Frontend URL
  NEXT_PUBLIC_OWN_URL: aHR0cHM6Ly9hcHAtZC5wcm9udGNsaW5pYy5jb20uYnI=  # https://app-d.prontclinic.com.br
  
  # Database Configuration
  DB_PRONT_CONNECTION: cG9zdGdyZXM=  # postgres
  DB_HOST: cG9zdGdyZXNxbC1kZXYtcncucHRjYy1kZXZlbG9wbWVudC5zdmMuY2x1c3Rlci5sb2NhbA==  # postgresql-dev-rw.ptcc-development.svc.cluster.local
  DB_PRONT_USERNAME: cHJvbnRjbGluaWM=  # prontclinic
  DB_PRONT_PASSWORD: VEsyOCptaSM3QFcmV25lIzRxbUVjMzNCeVImd3RZUg==  # TK28*mi#7@W&Wne#4qmEc33ByR&wtYR
  DB_PRONT_DATABASE: cHJvbnRjbGluaWNfZGV2X2Ri  # prontclinic_dev_db
  DB_PORT: NTQzMg==  # 5432
  
  # Schemas by Client
  NAME_SCHEMA_CLIENT: cHJvbnRjbGluaWNfY2xpZW50Xw==  # prontclinic_client_
  NAME_FUNCTION_SCHEMA: cHVibGljLmR1cGxpY2F0ZV9zY2hlbWE=  # public.duplicate_schema
  NAME_SCHEMA_REF: cHJvbnRjbGluaWNfY2xpX2RlZg==  # prontclinic_cli_def
  NAME_SCHEMA_GENERAL: Z2VuZXJhbF9wcm9udGNsaW5pYw==  # general_prontclinic
  
  # JWT Secret (base64 encoded)
  PRONTDENTAL_JWT_SECRET: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxSUVtbHZwUHk5M2xjNVl0WEJvVVVMWW1hSnFxakpacTMyQlZHZmFv  # MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqIEmlvpPy93lc5YtXBoUULYmaJqqjJZq32BVGfao
  
  # Evolution API Configuration
  EVOLUTION_API_URL: aHR0cHM6Ly9hcGktZmlsYS1kLnByb250Y2xpbmljLmNvbS5icg==  # https://api-fila-d.prontclinic.com.br
  EVOLUTION_API_TOKEN: U3ZpdUxkbTlIcEM3dXRKalRnSWpMREVkVnJKSGdydDk1Wjd2SDhWZDh5NnB6R0VtbVhQNEZhcVI2M2ozRnE4Nw==  # SviuLdm9HpC7utJjTgIjLDEdVrJHgrt95Z7vH8Vd8y6pzGEmmXP4FaqR63j3Fq87
  EVOLUTION_WEBHOOK_URL: aHR0cHM6Ly9hcGktZC5wcm9udGNsaW5pYy5jb20uYnIvd2hhdHNhcHAvZXZvbHV0aW9uLXdlYmhvb2s=  # https://api-d.prontclinic.com.br/whatsapp/evolution-webhook
  
  # ASAAS API Configuration
  ASAAS_API_URL: aHR0cHM6Ly9zYW5kYm94LmFzYWFzLmNvbS9hcGkvdjM=  # https://sandbox.asaas.com/api/v3
  ASAAS_API_TOKEN: aG1sZ18wMDBNemt3T0RBMk1XWTJPR00zTVdSbE1EVTJOV00zTXpKbE56Wm1OR1poWkdZNk9qTmxaR0kwWm1WbExUQXhPVEl0TkRZMk5TMWlOemRrTFRRNE1UZG1ZVGczTVRCaE1EbzZKR0ZoWTJoZk1HWXdORFV3T1RjdE1qQmpOeTAwWkdRNUxXRmxaRFl0WTJVeE16RXhOVGxqTkRKaQ==  # hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjNlZGI0ZmVlLTAxOTItNDY2NS1iNzdkLTQ4MTdmYTg3MTBhMDo6JGFhY2hfMGYwNDUwOTctMjBjNy00ZGQ5LWFlZDYtY2UxMzExNTljNDJi
  WEBHOOK_URL: aHR0cHM6Ly9wYWluZWwtZC5wcm9udGNsaW5pYy5jb20uYnIvYXBpL3N1YmFjY291bnRfd2ViaG9vaw==  # https://painel-d.prontclinic.com.br/api/subaccount_webhook
  ASAAS_ACCESS_WEBHOOK_TOKEN: cHJvbnRjbGluaWNfd2ViaG9vaw==  # prontclinic_webhook
