apiVersion: v1
kind: Service
metadata:
  name: redis-dev-service
  namespace: ptcc-development
  labels:
    app: redis-dev
    project: "ProntClinic"
    environment: "development"
spec:
  selector:
    app: redis-dev
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
