apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prontclinic-api-redis-pvc
  namespace: ptcc-development
  labels:
    app: prontclinic-api
    project: "ProntClinic"
    environment: "development"
    component: "redis"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "oci-bv" # Storage class do Oracle Cloud
