apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prontclinic-api-redis-pvc-fss
  namespace: ptcc-development
  labels:
    app: prontclinic-api
    component: redis
    project: "ProntClinic"
    environment: "development"
spec:
  accessModes:
    - ReadWriteMany  # ✅ Permite múltiplos pods!
  storageClassName: oci-fss
  resources:
    requests:
      storage: 10Gi  # FSS mínimo recomendado

