apiVersion: v1
kind: Secret
metadata:
  name: prontclinic-api-secret
  namespace: ptcc-development
  labels:
    app: prontclinic-api
    project: "ProntClinic"
    environment: "development"
type: Opaque
data:
  # Database Configuration
  DB_PRONT_HOST: cG9zdGdyZXNxbC1kZXYtcncucHRjYy1kZXZlbG9wbWVudC5zdmMuY2x1c3Rlci5sb2NhbA==  # postgresql-dev-rw.ptcc-development.svc.cluster.local
  DB_PRONT_USERNAME: cHJvbnRjbGluaWM=  # prontclinic
  DB_PRONT_PASSWORD: VEsyOCptaSM3QFcmV25lIzRxbUVjMzNCeVImd3RZUg==  # TK28*mi#7@W&Wne#4qmEc33ByR&wtYR
  DB_PRONT_DATABASE: cHJvbnRjbGluaWNfZGV2X2Ri  # prontclinic_dev_db
  DATABASE_URL: cG9zdGdyZXM6Ly9wcm9udGNsaW5pYzpUSzI4Km1pIzdAVyZXbmUjNHFtRWMzM0J5UiZ3dFlSQDE2My4xNzYuMjQ5LjE5Mjo1NDMyL3Byb250Y2xpbmljX2Rldl9kYg==  # postgres://prontclinic:TK28*mi#7@W&Wne#4qmEc33ByR&wtYR@163.176.249.192:5432/prontclinic_dev_db
  
  # Email Configuration
  MAIL_API_KEYi: bWQtTE1xTXB6aDFsQzBJaERYeW5mSTRIdw==  # md-LMqMpzh1lC0IhDXynfI4Hw
  MAIL_HOST: c210cC5ob3N0aW5nZXIuY29t  # smtp.hostinger.com
  MAIL_PORT: NDY1  # 465
  MAIL_USER: YXRlbmRpbWVudG9AY2xhaXJpcy5jb20uYnI=  # atendimento@clairis.com.br
  MAIL_PSW: Q2xhaXJpczk4MUBA  # Clairis981@@
  
  # JWT Configuration
  JWT_SECRET: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxSUVtbHZwUHk5M2xjNVl0WEJvVVVMWW1hSnFxakpacTMyQlZHZmFv  # MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqIEmlvpPy93lc5YtXBoUULYmaJqqjJZq32BVGfao
  JWT_SECRET_EXPIRES_IN: MTJo  # 12h
  JWT_REFRESH_SECRET: dzdtRW9yN013V2tYZitrREx0eHkzcWpMdW1CRUFCdTM5RmxqejtUc3BVM1BQN3dNWGNmSGlYZm03R2VibkFtWm9IeXZyWkxNZG0rUUlEQUFB  # w7mEor7MwWkXf+hDLtxy3qjLumBEABu39Fljz+TspU3PP7wMXcfHiXfmw8GebnQmZoHyvrZLMdm+QIDAQAB
  JWT_REFRESH_SECRET_EXPIRES_IN: MTJo  # 12h
  
  # Application URLs
  OWN_URL: aHR0cHM6Ly9hcGktZC5wcm9udGNsaW5pYy5jb20uYnI=  # https://api-d.prontclinic.com.br
  URL_FRONT: aHR0cHM6Ly9hcHAtZC5wcm9udGNsaW5pYy5jb20uYnI=  # https://app-d.prontclinic.com.br
  
  # S3 Bucket MINIO Configuration
  BUCKET_ENDPOINT: aHR0cHM6Ly9zMy1hcGktZC5wcm9udGNsaW5pYy5jb20uYnI=  # https://s3-api-d.prontclinic.com.br
  BUCKET_ACCESS_KEY_ID: dXNlci1pbWctcHJvbnRjbGluaWMtZA==  # user-img-prontclinic-d
  BUCKET_NAME: aW1nLXByb250Y2xpbmljLWQ=  # img-prontclinic-d
  BUCKET_SECRET_KEY: Y25Nb242b2NvcFpROGxUOEc2Q1Z4QURzNDNOeWlTQ1MwOTJNNw==  # cnMon6ocopZQ8lT8G6CVxADs43NyiSCS092M7
  
  # Digital Certificate Configuration
  AES_SECRET_KEY: eW43WnVqNWdHdjZYRlZxeVh4SGZxUT09  # yn7Zuj5oGz6XFVqyXxHfqQ==
  AES_IV: enhjdmJubTEyNDA5ODI9  # zxcvbnm1240982=
  
  # Evolution API Configuration
  EVOLUTION_API_URL: aHR0cHM6Ly9hcGktZmlsYS1kLnByb250Y2xpbmljLmNvbS5icg==  # https://api-fila-d.prontclinic.com.br
  EVOLUTION_API_TOKEN: U3ZpdUxkbTlIcEM3dXRKalRnSWpMREVkVnJKSGdydDk1Wjd2SDhWZDh5NnB6R0VtbVhQNEZhcVI2M2ozRnE4Nw==  # SviuLdm9HpC7utJjTgIjLDEdVrJHgrt95Z7vH8Vd8y6pzGEmmXP4FaqR63j3Fq87
  APP_URL: YXBpLWQucHJvbnRjbGluaWMuY29tLmJy  # api-d.prontclinic.com.br
  EVOLUTION_API_URL_CHAT: aHR0cHM6Ly9hcGktY2hhdC1kLnByb250Y2xpbmljLmNvbS5icg==  # https://api-chat-d.prontclinic.com.br
  EVOLUTION_API_TOKEN_CHAT: U3ZpdUxkbTlIcEM3dXRKalRnSWpMREVkVnJKSGdydDk1Wjd2SDhWZDh5NnB6R0VtbVhQNEZhcVI2M2ozRnE4Nw==  # SviuLdm9HpC7utJjTgIjLDEdVrJHgrt95Z7vH8Vd8y6pzGEmmXP4FaqR63j3Fq87
  APP_URL_CHAT: YXBpLWQucHJvbnRjbGluaWMuY29tLmJy  # api-d.prontclinic.com.br
  
  # Asaas Configuration
  ASAAS_SANDBOX_URL: aHR0cHM6Ly9zYW5kYm94LmFzYWFzLmNvbS9hcGkvdjM=  # https://sandbox.asaas.com/api/v3
  ASAAS_API_KEY: aG1sZ18wMDBNemt3T0RBMk1XWTJPR00zTVdSbE1EVTJOV00zTXpKbE56Wm1OR1poWkdZNk9qTmxaR0kwWm1WbExUQXhPVEl0TkRZMk5TMWlOemRrTFRRNE1UZG1ZVGczTVRCaE1EbzZKR0ZoWTJoZk1HWXdORFV3T1RjdE1qQmpOeTAwWkdRNUxXRmxaRFl0WTJVeE16RXhOVGxqTkRKaQ==  # hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OjNlZGI0ZmVlLTAxOTItNDY2NS1iNzdkLTQ4MTdmYTg3MTBhMDo6JGFhY2hfMGYwNDUwOTctMjBjNy00ZGQ5LWFlZDYtY2UxMzExNTljNDJi
  
  # Redis Configuration
  CACHE_REDIS_URI: cmVkaXM6Ly9yZWRpczEyM0Bwcm9udGNsaW5pYy1hcGktcmVkaXMtc2VydmljZS5wdGNjLWRldmVsb3BtZW50LnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMA==  # redis://redis123@prontclinic-api-redis-service.ptcc-development.svc.cluster.local:6379/0
  
  # Schemas by Client
  NAME_SCHEMA_CLIENT: cHJvbnRjbGluaWNfY2xpZW50Xw==  # prontclinic_client_
  NAME_FUNCTION_SCHEMA: cHVibGljLmR1cGxpY2F0ZV9zY2hlbWE=  # public.duplicate_schema
  NAME_SCHEMA_REF: cHJvbnRjbGluaWNfY2xpX2RlZg==  # prontclinic_cli_def
  NAME_SCHEMA_GENERAL: Z2VuZXJhbF9wcm9udGNsaW5pYw==  # general_prontclinic